In [1]:
import pandas as %pd

In [3]:
info = {
    "Name":["Rahul","Harshita","Shradha"],
    "CGPA":[9.5,7.5,8.5],
}

df = pd.DataFrame(info)
print(df)
df

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

       Name  CGPA
0     Rahul   9.5
1  Harshita   7.5
2   Shradha   8.5

In [10]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1

In [16]:
s = pd.Series([23,24,25,26],index = ["Adam","Eve","Bob","Charlie"])
print(s)
print(s["Adam"])
print(s["Bob"])

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
23
25

In [19]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])
print(s1+s2)
s1[0] = 100
print(s1[0])
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
100
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [23]:
#Dataframe
info = {
    "Name":["Adam","Eve","Bob"],
    "Age":[23,24,25],
    "GPA":[9.5,8.6,7.2]
}
df = pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

   Name  Age  GPA
0  Adam   23  9.5
1   Eve   24  8.6
2   Bob   25  7.2
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [25]:
df = pd.DataFrame([["Adam",23],["Bob",23],["Eve",23]],columns = ["Name","Age"])
df

   Name  Age
0  Adam   23
1   Bob   23
2   Eve   23

In [26]:
import numpy as np
np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [27]:
#csv data
df = pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [28]:
#json data
df = pd.read_json("employee_data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [39]:
#Methods
df.head() #starting 5 rows
df.tail() #last 5 values
df.sample() # any 1 random value
df.info()
df.shape
df.describe()
df.columns
df.nunique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [29]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [43]:
# AQI DataSet

df = pd.read_csv("globalAirQuality.csv")

df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [56]:
#selecting data
df["city"]
df[["city","aqi"]]
df.loc[0]
df.loc[0:2] #ending index in inclusive
df.iloc[0:3] #ending index is exclusive
#cells - row,col
df.loc[0:2,["city","aqi"]]
df.iloc[0:3,[2,3]]

       city  latitude
0  New York    40.713
1  New York    40.713
2  New York    40.713

In [44]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [71]:
df.columns
#df.loc[0:2,["country","city","latitude","longitude"]]
df.iloc[0:3,1:5]
# cell
df.at[0,"city"]
df.iat[0,2]
cities = df["city"].copy()
cities[0] = "Mumbai"
df
cities

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [82]:
#filtering of data
df[df["aqi"]>100]
df[(df["aqi"]>100) & (df["temperature"]>30)]
df[(df["aqi"]>100) & (df["temperature"]<30)]
aqi_data = df[(df["aqi"]>100) & (df["temperature"]>30)][["city","aqi"]]
aqi_data.iloc[0]

city    New York
aqi          155
Name: 6, dtype: object

In [87]:
#query method it returns the copy
aqi_val = 100
df.query("aqi>100 & temperature>30")[["city","aqi"]]
df.query("aqi>@aqi_val & temperature>30")[["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [98]:
#Cleaning Data - missing values

df = pd.read_csv("raw_data.csv")
df.isnull()
df.isnull().sum()
df.dropna() #row drop
df.dropna(axis = 1) #col drop
df.fillna(0)

clean_data = df.copy()
age_mean = clean_data["age"].mean()
clean_data["age"] = clean_data["age"].fillna(age_mean)
clean_data

df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [89]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [104]:
#Handle Duplicates
df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()
df2 = df.copy()
df.drop_duplicates(inplace=True)

In [115]:
#Data Types
df.dtypes

df2 = df.copy()
df2 = df2.fillna(0).copy()
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [116]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [107]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [124]:
aqi_data = pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"].dtype
aqi_data["timestamp"] = pd.to_datetime(aqi_data["timestamp"]).copy()
aqi_data["timestamp"].dtype
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [133]:
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()
df["name"].str.split(" ")
df["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [126]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [153]:
#Feature Engineering
df2 = df.copy()
df2["tax"] = df2["income"].apply(lambda x:"20%" if x>=50000 else "10%")

gender_map = {"Male":"M","Female":"F","Unknown":"U"}
df2["gender"] = df2["gender"].map(gender_map)
df2 = df2.assign(new_income = df2["income"]*1.1)
df2["country"] = df2["country"].replace("USA","United States")
df2
df2.columns = ["ID","Name","Age","Country","Gender","Income","Tax","New_Income"]
df2
df2.rename(columns={"Income":"Salary"})
df2.rename(index = {1:"First"})
df2.sort_values("Income")
sorted_df = df2.sort_values("Income",ascending=False)
sorted_df.sort_index()

    ID          Name   Age        Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
1    1      John Doe  29.0  United States      M  55000.0  20%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  20%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  20%     63800.0

In [154]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [163]:
df2 = df.copy()
df2.columns
new_col_order = [col for col in df2.columns if col!="id"] + ["id"]
print(new_col_order)
df2[new_col_order]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [185]:
df2 = df.copy()
df2.drop_duplicates(inplace=True)
df2 = df2.fillna(0)
df2 = df2.sort_values("income")
df2 = df2.reset_index(drop=True)
df2.to_csv("sorted_data.csv")

In [184]:
df2

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0

In [186]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [200]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()
df.groupby("gender")["income"].mean()

df.groupby("country")["income"].agg(["mean","min","max"])
df.groupby("country")["income"].agg(average_sal="mean",minimum_sal="min",maximum_sal="max")
df.groupby("country").agg({
    "income":"mean",
    "age":"mean"
})
df.groupby("country").agg(
    max_salary=("income","max"),
    avg_age=("age","mean")
)

         max_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5

In [211]:
#Concatentation

df1 = pd.DataFrame({
    "id":[1,2,3],
    "name":["Adam","Eve","Bob"]
})
df2 = pd.DataFrame({
    "id":[4,5,6],
    "name":["Charlie","Fester","Gilian"]
})

pd.concat([df1,df2]) #row wise concationation
pd.concat([df1,df2],ignore_index=True)

pd.concat([df1,df2],axis=1) #Col wise concationation

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6   Gilian

In [207]:
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [208]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian