In [2]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [3]:
df = datasets.load_iris(as_frame=True).frame

In [4]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [6]:
df.isnull().sum()
df.shape

(150, 5)

In [7]:
X = df.drop(columns=["target"])
Y = df["target"]

In [8]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=42,stratify=Y)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
#Model
svc = SVC()
svc.fit(X_train_scaled,Y_train)

SVC()

In [15]:
Y_pred = svc.predict(X_test_scaled)

In [18]:
#Evaluate
from sklearn.metrics import accuracy_score,classification_report,f1_score
print("Accuracy:",accuracy_score(Y_test,Y_pred))
print("Classification Report:",classification_report(Y_test,Y_pred))
print("F1 Score:", f1_score(Y_test, Y_pred, average="weighted"))

Accuracy: 0.9333333333333333
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

F1 Score: 0.9332591768631814

In [21]:
# Linear Kernal
svc = SVC(kernel="linear")
svc.fit(X_train_scaled,Y_train)
Y_pred = svc.predict(X_test_scaled)
print("accuracy:",accuracy_score(Y_test,Y_pred))
print("Classification Report:",classification_report(Y_test,Y_pred))
print("F1 Score:", f1_score(Y_test, Y_pred, average="weighted"))

accuracy: 0.9111111111111111
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.82      0.93      0.87        15
           2       0.92      0.80      0.86        15

    accuracy                           0.91        45
   macro avg       0.92      0.91      0.91        45
weighted avg       0.92      0.91      0.91        45

F1 Score: 0.9107142857142857

In [23]:
# Polynomial Kernal
svc = SVC(kernel="poly")
svc.fit(X_train_scaled,Y_train)
Y_pred = svc.predict(X_test_scaled)
print("accuracy:",accuracy_score(Y_test,Y_pred))
print("Classification Report:",classification_report(Y_test,Y_pred))
print("F1 Score:", f1_score(Y_test, Y_pred, average="weighted"))

accuracy: 0.8666666666666667
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.71      1.00      0.83        15
           2       1.00      0.60      0.75        15

    accuracy                           0.87        45
   macro avg       0.90      0.87      0.86        45
weighted avg       0.90      0.87      0.86        45

F1 Score: 0.8611111111111112

In [24]:
# Sigmoid Kernal
svc = SVC(kernel="sigmoid")
svc.fit(X_train_scaled,Y_train)
Y_pred = svc.predict(X_test_scaled)
print("accuracy:",accuracy_score(Y_test,Y_pred))
print("Classification Report:",classification_report(Y_test,Y_pred))
print("F1 Score:", f1_score(Y_test, Y_pred, average="weighted"))

accuracy: 0.9111111111111111
Classification Report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.92      0.80      0.86        15
           2       0.82      0.93      0.87        15

    accuracy                           0.91        45
   macro avg       0.92      0.91      0.91        45
weighted avg       0.92      0.91      0.91        45

F1 Score: 0.9107142857142857

In [26]:
C_vals = [0.5,1,2,3,4,5]
for c_val in C_vals:
    svc = SVC(C=c_val,kernel="rbf")
    svc.fit(X_train_scaled,Y_train)
    Y_pred = svc.predict(X_test_scaled)
    print("c=",c_val,"& accuracy:",accuracy_score(Y_test,Y_pred))

c= 0.5 & accuracy: 0.9111111111111111
c= 1 & accuracy: 0.9333333333333333
c= 2 & accuracy: 0.9111111111111111
c= 3 & accuracy: 0.9111111111111111
c= 4 & accuracy: 0.9333333333333333
c= 5 & accuracy: 0.9333333333333333